name: test

# This workflow run tests and build for each push

on:
  push:
    branches:
      - master

jobs:
  test-db:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2  
      - name: Build
        run:  cargo build --verbose
      - name: Test
        run: cargo test --verbose          
