name: CI

# This workflow run tests and build for each push

on:
  push:
    branches:
      - master

jobs:
  test-db:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2  
      - name: Test
        run: |
          cargo check
          cargo test --all          

      - name: Build
        run: |
          cargo build